version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version; Install Leiningen; Install Clojure CLI tools
      - cd $HOME
      - pip install --upgrade awscli
      - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; mv lein /bin;
      - LEIN_ROOT=true lein
      - mkdir clj_tools_install; cd clj_tools_install
      - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh; chmod +x linux-install-1.10.0.411.sh; ./linux-install-1.10.0.411.sh
      - cd $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - echo "\nContents of the base directory:\n"
      - ls -al
      - echo
      - echo Test started on `date`
      - lein test
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - LEIN_ROOT=true lein uberjar
      - mv target/pedestal-lambda-0.0.1-SNAPSHOT-standalone.jar .
      - jar xf pedestal-lambda-0.0.1-SNAPSHOT-standalone.jar
      - rm -rf target src buildspec.yml project.clj pom.xml pedestal-lambda-0.0.1-SNAPSHOT-standalone.jar.jar
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  files:
    - template-export.yml
    - template-configuration.json
