name: Publish pedestal.io
on:
  push:
    branches:
      - master
      # And, eventually, maint branches

jobs:
  notify-pedestal-io:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: pedestal/pedestal-docs
          token: $${ secrets.PUBLISH_PEDESTAL_IO_PAT }}
          event-type: pedestal_master_commit
