name: Publish pedestal.io
on:
  push:
    branches:
      - master
      # And, eventually, maint branches

jobs:
  notify-pedestal-io:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        repository: pedestal/pedestal-docs
        token: $${ secrets.PUBLISH_PEDESTAL_IO_PAT }}
        event-type: pedestal_master_commit
